spring:
  profiles.active: test
---
spring:
  profiles: default
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/lc_tutorials
  username: root
  password:
  schema:
  data:
---
spring:
  profiles: test
spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test;MODE=MySQL
  schema: schema.sql
  data: data.sql